### ISSUE TITLE
Create a release for raspberry pi

### ISSUE THREAD

**Issue by brjann** [tzzh/pod-tzzh-mail#1]
It would be great with a linux aarch64 release of tzzh mail for Raspberry pi.

**Comment by ccfontes** [comment]
Apologies in advance for issue necro.

Tried running this pod in docker container in linux via multipass on an M1. Getting this error:
```
(pods/load-pod 'tzzh/mail "0.0.2")
^--- No executable found for pod tzzh/mail (0.0.2) and OS Linux/aarch64
```
Support appreciated. 🥺

**Comment by ccfontes** [comment]
Gave it a stab, and works on my local linux/aarch64.
Compiled and ran `load-pod` + `(require '[pod.tzzh.mail :refer [send-mail]])`. No issues so far.
I'll try to upload the pod to the registry tomorrow or so and do some integrated testing.

**Comment by tzzh** [comment]
@ccfontes thanks for re-raising - I have just made a new release with arm64 binaries. Let me know if that works and I can add it to the pod registry.

**Comment by ccfontes** [comment]
Great timing. I was wondering how to go about doing this well.

I just wanted for now to make an ad-hoc release for arm64, and test e2e before PRing manifest to the pod registry, but I couldn't find a way.

Will test soon and let you know. Thank you so much!

**Comment by ccfontes** [comment]
@tzzh , used your [pod-tzzh-mail_Linux_arm64.tar.gz](https://github.com/tzzh/pod-tzzh-mail/releases/download/v0.0.3/pod-tzzh-mail_Linux_arm64.tar.gz) 0.0.3 release and works for the simple test I've made before:
```
Compiled and ran load-pod + (require '[pod.tzzh.mail :refer [send-mail]]). No issues so far.
```

If you want I can go a bit out of my way to make a more thorough manual testing, but if you're comfortable, lets test further with the new version in pod registry.
